import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.css";
import { buildClient } from "@/services/build-client";
import React from "react";
import { Header } from "@/components/header";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getCurrentUser() {
  const client = buildClient();
  const { data } = await client.get("/api/users/currentuser");
  return data;
}

export default async function RootLayout({
  children,
}: {
  children: JSX.Element;
}) {
  const { currentUser } = await getCurrentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header currentUser={currentUser} />
        {children}
      </body>
    </html>
  );
}
